global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Frontend
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Workers
  - job_name: 'expand-worker'
    static_configs:
      - targets: ['expand-worker-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'serp-worker'
    static_configs:
      - targets: ['serp-worker-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-service:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-service:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # OpenSearch
  - job_name: 'opensearch'
    static_configs:
      - targets: ['opensearch-service:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

  # ClickHouse
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-service:8123']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # NATS
  - job_name: 'nats'
    static_configs:
      - targets: ['nats-service:8222']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio-service:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  # Kubernetes
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  - job_name: 'kubernetes-service-endpoints'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
