apiVersion: v1
kind: Secret
metadata:
  name: seo-tool-secrets
type: Opaque
data:
  # Database
  DB_PASSWORD: c2VvX3Bhc3N3b3Jk  # base64 encoded
  DB_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  
  # Redis
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=
  
  # OpenSearch
  OPENSEARCH_USERNAME: YWRtaW4=
  OPENSEARCH_PASSWORD: YWRtaW5fcGFzc3dvcmQ=
  
  # S3/MinIO
  S3_ACCESS_KEY: bWluaW9fYWNjZXNzX2tleQ==
  S3_SECRET_KEY: bWluaW9fc2VjcmV0X2tleQ==
  
  # API Keys
  SERP_API_KEY: c2VycF9hcGlfa2V5
  OPENAI_API_KEY: b3BlbmFpX2FwaV9rZXk=
  
  # JWT
  JWT_SECRET: anNvbnNlY3JldGtleQ==
  SESSION_SECRET: c2Vzc2lvbnNlY3JldGtleQ==
  
  # SSL/TLS
  SSL_CERT: ""
  SSL_KEY: ""
  
  # Monitoring
  GRAFANA_ADMIN_PASSWORD: Z3JhZmFuYV9hZG1pbg==
